export const CHATBOT_GET_RESPONSE_REQUEST = 'CHATBOT_GET_RESPONSE_REQUEST';
export const CHATBOT_GET_RESPONSE_SUCCESS = 'CHATBOT_GET_RESPONSE_SUCCESS';
export const CHATBOT_GET_RESPONSE_FAIL = 'CHATBOT_GET_RESPONSE_FAIL';
