export const USER_GET_DETAILS_REQUEST = 'USER_GET_DETAILS_REQUEST';
export const USER_GET_DETAILS_SUCCESS = 'USER_GET_DETAILS_SUCCESS';
export const USER_GET_DETAILS_FAIL = 'USER_GET_DETAILS_FAIL';

export const USER_UPDATE_DETAILS_REQUEST = 'USER_UPDATE_DETAILS_REQUEST';
export const USER_UPDATE_DETAILS_SUCCESS = 'USER_UPDATE_DETAILS_SUCCESS';
export const USER_UPDATE_DETAILS_FAIL = 'USER_UPDATE_DETAILS_FAIL';
