export const VERIFICATION_SEND_REQUEST = 'VERIFICATION_SEND_REQUEST';
export const VERIFICATION_SEND_SUCCESS = 'VERIFICATION_SEND_SUCCESS';
export const VERIFICATION_SEND_FAIL = 'VERIFICATION_SEND_FAIL';

export const VERIFICATION_CONFIRM_REQUEST = 'VERIFICATION_CONFIRM_REQUEST';
export const VERIFICATION_CONFIRM_SUCCESS = 'VERIFICATION_CONFIRM_SUCCESS';
export const VERIFICATION_CONFIRM_FAIL = 'VERIFICATION_CONFIRM_FAIL';

export const VERIFICATION_STATE_REFRESH = 'VERIFICATION_STATE_REFRESH';
