export const fashion = [
    {
        name: 'JACK & JONES Black Logo Hoody',
        category: 'Thời trang',
        price: 1100000,
        countInStock: 150,
        brand: 'Jack & Jones',
        weight: 550,
        description:
            'Bạn cần một thứ thiết yếu bình thường? Chọn bộ đồ nam yêu thích mới của bạn từ JACK & JONES tại Suit Direct ngay hôm nay. \n\nĐược làm từ chất liệu vải cotton mềm mại để tạo sự thoải mái tinh khiết, áo có in logo thương hiệu đặc trưng trên nền màu đen tuyền. \n\nĐược thành lập và có trụ sở tại Đan Mạch, JACK & JONES cung cấp cho người tiêu dùng hiện đại những bộ sưu tập dành cho mọi dịp và xu hướng thời trang. Ban đầu được thành lập như một thương hiệu quần jean, JACK & JONES giờ đây cũng cung cấp các sản phẩm may đo, quần áo thể thao đô thị, giày dép và phụ kiện.',
        images: [
            'https://i.ibb.co/ggCcCsr/jack-jones-black-logo-hoody-01.jpg',
            'https://i.ibb.co/w0Vp6Kw/jack-jones-black-logo-hoody-02.jpg',
            'https://i.ibb.co/Z6hQczZ/jack-jones-black-logo-hoody-03.jpg',
            'https://i.ibb.co/s13M9tj/jack-jones-black-logo-hoody-04.jpg',
            'https://i.ibb.co/J3zsLqb/jack-jones-black-logo-hoody-05.jpg',
            'https://i.ibb.co/PFcNwvX/jack-jones-black-logo-hoody-06.jpg',
        ],
    },
    {
        name: 'JEFF BANKS V Neck Jumper',
        category: 'Thời trang',
        price: 800000,
        countInStock: 30,
        brand: 'Jett Banks',
        weight: 250,
        description:
            'Kỹ thuật thủ công của Jeff Banks bao gồm cả phong cách sartorial và sự thoải mái tuyệt vời. Mua sắm của bạn ngay bây giờ tại Suit Direct. \n\nĐược làm thủ công cẩn thận, chiếc áo liền quần cổ chữ V này được làm từ bông tinh khiết cho cảm giác sang trọng, mềm mại khi chạm vào. Với thương hiệu mảng bám kim loại cổ điển ở bên cạnh, chiếc áo liền quần này được thiết kế để tạo sự thoải mái và bền bỉ. \n\nMỗi tác phẩm của Jeff Banks đều được chế tác tỉ mỉ dành cho nam giới. Mặc của bạn với niềm tự hào.',
        images: [
            'https://i.ibb.co/yQ4cr6N/jeff-banks-v-neck-jumper-01.jpg',
            'https://i.ibb.co/F0q4kBt/jeff-banks-v-neck-jumper-02.jpg',
            'https://i.ibb.co/X5bfC0Q/jeff-banks-v-neck-jumper-03.jpg',
            'https://i.ibb.co/bdcCL5c/jeff-banks-v-neck-jumper-04.jpg',
            'https://i.ibb.co/8jzG43c/jeff-banks-v-neck-jumper-05.jpg',
        ],
    },
    {
        name: 'JEFF BANKS Viscose Floral Print Shirt',
        category: 'Thời trang',
        price: 1200000,
        countInStock: 120,
        brand: 'Jett Banks',
        weight: 200,
        description:
            'Kỹ thuật thủ công của Jeff Banks bao gồm cả phong cách sartorial và sự thoải mái tuyệt vời. Được làm từ 100% viscose, chiếc áo sơ mi giản dị này mang đến một sự bổ sung lý tưởng cho tủ quần áo của bất kỳ người đàn ông nào. \n\nVới họa tiết in hoa nhiệt đới với chút hồng đậm hoàn hảo cho mùa hè, mẫu áo này được tạo kiểu với cổ áo tôn dáng và có thể dễ dàng kết hợp với quần chinos nam hoặc quần tây nam. Mua sắm của bạn ngay bây giờ tại Suit Direct.',
        images: [
            ' https://i.ibb.co/rMhzJGM/jeff-banks-viscose-floral-print-shirt-01.jpg',
            ' https://i.ibb.co/sJ6nCKy/jeff-banks-viscose-floral-print-shirt-02.jpg',
            ' https://i.ibb.co/qsfKWj8/jeff-banks-viscose-floral-print-shirt-03.jpg',
            ' https://i.ibb.co/m9g5r4M/jeff-banks-viscose-floral-print-shirt-04.jpg',
        ],
    },
    {
        name: 'LIMEHAUS Burgundy Texture Slim Suit',
        category: 'Thời trang',
        price: 2100000,
        countInStock: 60,
        brand: 'Limehaus',
        weight: 1250,
        description:
            'Một bộ vest đỏ burgundy thời trang dành cho nam của Limehaus - với chất liệu vải mềm mại và ve áo màu đen, phong cách, độc đáo và linh hoạt. \n\nBộ quần áo mỏng vừa vặn này là một nhà thiết kế xu hướng thực sự, với một điểm nhấn là độ giãn rộng rãi và phối màu đỏ đậm, tạo nên một nét độc đáo cho những bộ lễ phục truyền thống hoặc bộ đồ dạ tiệc. \n\nMột bộ đồ hai mảnh sành điệu cho bất kỳ dịp nào, với ảnh hưởng của di sản kết hợp với sự đổi mới và thoải mái hiện đại - lý tưởng cho các bữa tiệc Giáng sinh và hơn thế nữa.',
        images: [
            'https://i.ibb.co/8gB9Vrg/limehaus-burgundy-texture-slim-suit-01.jpg',
            'https://i.ibb.co/Sv5wy08/limehaus-burgundy-texture-slim-suit-02.jpg',
            'https://i.ibb.co/KctgC6t/limehaus-burgundy-texture-slim-suit-03.jpg',
            'https://i.ibb.co/z2vgTS6/limehaus-burgundy-texture-slim-suit-04.jpg',
            'https://i.ibb.co/Xzjkjst/limehaus-burgundy-texture-slim-suit-05.jpg',
            'https://i.ibb.co/hdRJ3jQ/limehaus-burgundy-texture-slim-suit-06.jpg',
            'https://i.ibb.co/j4xngq9/limehaus-burgundy-texture-slim-suit-07.jpg',
            'https://i.ibb.co/f2XLqB0/limehaus-burgundy-texture-slim-suit-08.jpg',
            'https://i.ibb.co/z2Ch3Ww/limehaus-burgundy-texture-slim-suit-09.jpg',
        ],
    },
    {
        name: 'LIMEHAUS Plain Blue Panama Slim Fit Suit',
        category: 'Thời trang',
        price: 2500000,
        brand: 'Limehaus',
        weight: 1350,
        description:
            'Limehaus là một người đi đầu trong xu hướng thời trang nam giới, với những bộ suit được cắt may mỏng hơn bình thường. Chúng tôi khuyên bạn nên thay đổi kích thước để có được sự phù hợp hoàn hảo. \n\nLý tưởng cho các quy tắc ăn mặc trang trọng, bộ vest nam ba mảnh này tự hào với chất liệu vải panama để đảm bảo sự thoải mái trong mọi thời tiết, với dáng ôm vừa vặn thoải mái và phối màu hải quân trơn chuyên nghiệp. \n\nĐược cắt theo khung và được thiết kế để tạo ra một hình bóng đơn giản, sắc nét, bộ vest truyền thống này là lựa chọn hoàn hảo để người chuyên nghiệp tạo ấn tượng vào bất kỳ dịp nào - cho dù là trang phục hàng ngày ở văn phòng hay sự kiện trang trọng - và có thể giặt bằng máy, khiến nó trở nên linh hoạt và dễ chăm sóc. \n\nMang dấu ấn chất lượng của Limehaus, bộ vest vừa vặn, thoải mái được thiết kế riêng này tự hào với nét hiện đại của phong cách truyền thống, với nét tinh tế tự nhiên, hoàn hảo cho bất kỳ dịp nào.',
        images: [
            'https://i.ibb.co/QPCvRYZ/limehaus-plain-blue-panama-slim-fit-jacket-01.jpg',
            'https://i.ibb.co/Z85752L/limehaus-plain-blue-panama-slim-fit-jacket-02.jpg',
            'https://i.ibb.co/SwLXg0d/limehaus-plain-blue-panama-slim-fit-jacket-03.jpg',
            'https://i.ibb.co/Tkych8g/limehaus-plain-blue-panama-slim-fit-jacket-04.jpg',
            'https://i.ibb.co/NtZgx0y/limehaus-plain-blue-panama-slim-fit-jacket-05.jpg',
            'https://i.ibb.co/TmKYhGs/limehaus-plain-blue-panama-slim-fit-jacket-06.jpg',
            'https://i.ibb.co/fp0fp4B/limehaus-plain-blue-panama-slim-fit-jacket-07.jpg',
            'https://i.ibb.co/9ypLY0F/limehaus-plain-blue-panama-slim-fit-jacket-08.jpg',
            'https://i.ibb.co/Hhwntkv/limehaus-plain-blue-panama-slim-fit-jacket-09.jpg',
            'https://i.ibb.co/41zDDKY/limehaus-plain-blue-panama-slim-fit-jacket-10.jpg',
        ],
    },
    {
        name: 'MELKA Karlskrona Double Face Shirt',
        category: 'Thời trang',
        price: 500000,
        countInStock: 20,
        brand: 'Melka',
        weight: 120,
        description:
            'Sơ mi vải đôi để biến hóa tủ quần áo của bạn - phong cách Melka. giới thiệu Karlskrona độc đáo, một chiếc áo sơ mi cotton nhẹ với sự khác biệt, với tay áo dài, túi ngực vá và cài cúc xuống, cổ áo cổ điển lấy cảm hứng từ kiểu dáng Oxford truyền thống của chúng tôi. \n\nVới chất liệu vải nhẹ, hai mặt, chiếc cúc áo màu xanh nước biển này có lớp vải trơn màu xanh nước biển được xếp trên một lớp vải bên trong đã được kiểm tra theo gam màu Melka tự nhiên - tạo ra một bộ quần áo có họa tiết độc đáo với nhiều kích thước và chi tiết hơn. \n\nMột biến thể cho bất kỳ tủ quần áo nào - áo sơ mi cotton sang trọng của nam giới, với vải cotton thương mại công bằng và nhãn hiệu Melka tab. Karlskrona là chiếc áo thể hiện hoàn hảo đặc tính Melka. consectetur adipisicing elit. Sed quis impedit corrupti sequi culpa illum iste dolor tempore alias ipsa atque dolorem, suscipit voluptatibus magnam voluptates aliquam nobis. Non, harum?',
        images: [
            'https://i.ibb.co/QfCt4Rh/melka-karlskrona-double-face-shirt-01.jpg',
            'https://i.ibb.co/0yLp8bK/melka-karlskrona-double-face-shirt-02.jpg',
            'https://i.ibb.co/Xz7srrh/melka-karlskrona-double-face-shirt-03.jpg',
            'https://i.ibb.co/HKZm3F8/melka-karlskrona-double-face-shirt-04.jpg',
            'https://i.ibb.co/fxyx3gx/melka-karlskrona-double-face-shirt-05.jpg',
            'https://i.ibb.co/gW2X2FK/melka-karlskrona-double-face-shirt-06.jpg',
        ],
    },
    {
        name: 'PIERRE CARDIN Navy Twill Regular Fit Suit Jacket',
        category: 'Thời trang',
        price: 1000000,
        countInStock: 10,
        brand: 'Pierre Cardin',
        weight: 1200,
        description:
            'Trông thông minh và phong cách trong dòng sản phẩm Pierre Cardin cổ điển. Tất cả các bộ quần áo đều được may vừa vặn để tạo sự thoải mái và có áo khoác 2 cúc với ve áo có khía. Chúng tôi cũng cung cấp nhiều loại cà vạt và áo sơ mi để bổ sung cho bộ đồ mới của bạn.',
        images: [
            'https://i.ibb.co/G5sTrKP/pierre-cardin-navy-twill-regular-fit-suit-jacket-01.jpg',
            'https://i.ibb.co/WPRfsqR/pierre-cardin-navy-twill-regular-fit-suit-jacket-02.jpg',
            'https://i.ibb.co/gjHFhW8/pierre-cardin-navy-twill-regular-fit-suit-jacket-03.jpg',
            'https://i.ibb.co/PQSLpg6/pierre-cardin-navy-twill-regular-fit-suit-jacket-04.jpg',
        ],
    },
    {
        name: 'RACING GREEN Charcoal Melton Overcoat',
        category: 'Thời trang',
        price: 1900000,
        countInStock: 12,
        brand: 'Racing Green',
        weight: 1800,
        description:
            'Chiếc áo khoác len pha trộn màu xám đậm này là một cách độc đáo để tạo phong cách cho bất kỳ tủ quần áo nào - một chiếc áo khoác hàng đầu dành cho nam giới lấy cảm hứng từ cách may cổ điển của Anh. \n\nVới ve áo xẻ rãnh, thắt nút ba buton ở ngực duy nhất, vừa vặn được thiết kế riêng và nhiều không gian túi, chiếc áo khoác len nam này lý tưởng cho mọi tủ quần áo. \n\nÁo khoác nam màu xám đậm cổ điển dành cho mọi dịp của Racing Green. Lý tưởng cho một người đàn ông khi di chuyển, bộ sưu tập Racing Green dựa trên hiệu suất. Độ bền, đường cắt kiểu cách và sự vừa vặn, tinh tế đã làm cho cái tên trở thành huyền thoại trong những bộ vest đương đại, tinh tế, lý tưởng để tạo ấn tượng, cân bằng với phong cách Anh Quốc không bao giờ lỗi mốt.',
        images: [
            'https://i.ibb.co/0Zyj5Mk/racing-green-charcoal-melton-overcoat-01.jpg',
            'https://i.ibb.co/SyD9SRG/racing-green-charcoal-melton-overcoat-02.jpg',
            'https://i.ibb.co/JpwcSM1/racing-green-charcoal-melton-overcoat-03.jpg',
            'https://i.ibb.co/LrKgsdp/racing-green-charcoal-melton-overcoat-04.jpg',
            'https://i.ibb.co/1v74vgQ/racing-green-charcoal-melton-overcoat-05.jpg',
        ],
    },
    {
        name: 'SCOTT BY THE LABEL Navy Blazer',
        category: 'Thời trang',
        price: 2900000,
        countInStock: 0,
        brand: 'Scott By The Label',
        weight: 1300,
        description:
            'Một chiếc áo khoác len nam pha trộn màu xanh hải quân đầy phong cách của Scott by the Label, với kiểu dáng cổ điển, linh hoạt. \n\nTự hào với ve áo, lỗ thông hơi bên hông và hai cúc cài, chiếc áo khoác màu xanh đậm này là một món đồ cổ điển ngay lập tức cho bất kỳ tủ quần áo trang trọng nào. \n\nMột tác phẩm kinh điển của Scott by the Label.',
        images: [
            'https://i.ibb.co/0GXJ2SC/scott-by-the-label-navy-blazer-02.jpg',
            ' https://i.ibb.co/ygr4yGQ/scott-by-the-label-navy-blazer-01.jpg',
        ],
    },
    {
        name: 'SCOTT & TAYLOR Satin Shawl Lapel Regular Fit Dresswear Jacket',
        category: 'Thời trang',
        price: 2300000,
        countInStock: 100,
        brand: 'Scott & Taylor',
        weight: 1450,
        description:
            'Bộ lễ phục phong cách này là bộ vest đen Dresswear tinh túy dành cho một người đàn ông đang tìm kiếm ấn tượng tích cực trong một cuộc tình với cà vạt đen. \n\nĐược thiết kế theo phong cách may đo truyền thống, bộ tuxedo hai mảnh này tự hào với sự vừa vặn thoải mái, ve áo tương phản trong thiết kế khăn choàng và kiểu dáng sắc nét kết hợp giữa phong cách Tuxedo truyền thống và kiểu dáng Gatsby mang tính biểu tượng với sự thoải mái và linh hoạt hiện đại. \n\nScott và Taylor là bộ đồ thiết thực dành cho các quý ông hiện đại, và đối với những người muốn gây ấn tượng trong các buổi tụ họp với bạn bè và gia đình, thương hiệu Nhân dịp của họ là một người bạn đồng hành ấn tượng. Hoàn hảo cho các bữa tiệc Giáng sinh!',
        images: [
            'https://i.ibb.co/y0XGp5J/scott-taylor-satin-shawl-lapel-regular-fit-dresswear-jacket-01.jpg',
            'https://i.ibb.co/FsZxZRH/scott-taylor-satin-shawl-lapel-regular-fit-dresswear-jacket-02.jpg',
            'https://i.ibb.co/415Z9x3/scott-taylor-satin-shawl-lapel-regular-fit-dresswear-jacket-03.jpg',
            'https://i.ibb.co/xjNsMjf/scott-taylor-satin-shawl-lapel-regular-fit-dresswear-jacket-04.jpg',
            'https://i.ibb.co/23QQmBf/scott-taylor-satin-shawl-lapel-regular-fit-dresswear-jacket-05.jpg',
            'https://i.ibb.co/7z3CQ9D/scott-taylor-satin-shawl-lapel-regular-fit-dresswear-jacket-06.jpg',
            'https://i.ibb.co/qytRJKd/scott-taylor-satin-shawl-lapel-regular-fit-dresswear-jacket-07.jpg',
            'https://i.ibb.co/16P9hx2/scott-taylor-satin-shawl-lapel-regular-fit-dresswear-jacket-08.jpg',
            'https://i.ibb.co/VwnywvL/scott-taylor-satin-shawl-lapel-regular-fit-dresswear-jacket-09.jpg',
        ],
    },
];
